// @vitest-environment node
import { describe, it, expect } from 'vitest';
import { ESLint } from 'eslint';
import path from 'path';
import {
  CONSOLIDATED_RESTRICTED_SYNTAX,
  PLATFORM_PRIMITIVE_PATHS,
} from '../../eslint.helpers.js';

/**
 * Meta-test for `eslint.config.js` flat-config resolution.
 *
 * Why this test exists:
 *   In flat config, when multiple config blocks both match a file and
 *   both define the same rule (`no-restricted-syntax` or
 *   `no-restricted-imports`), ESLint REPLACES the rule's options entirely
 *   — it does NOT merge the options arrays. The later matching block wins.
 *
 *   This is the silent-failure mode that allowed the Site Settings
 *   Event Ownership rule to look enforced (lint passed, smoke test
 *   appeared green at the file level) while actually being dropped
 *   from the fixture file's resolved config because the rule's own
 *   `ignores` block excluded the fixture.
 *
 *   This meta-test inspects the *resolved* config (`calculateConfigForFile`)
 *   for representative source files and asserts that EVERY entry in
 *   `CONSOLIDATED_RESTRICTED_SYNTAX` and `PLATFORM_PRIMITIVE_PATHS`
 *   survives. The assertions are GENERATED by iterating over the source
 *   arrays — adding a new selector or banned import to those arrays
 *   automatically extends the test, so there is no second-place-to-edit
 *   hazard. The only manual surface left is `defineScopedDoctrine()` /
 *   `defineScopedImportDoctrine()` callers (which is where the helper
 *   guarantees concatenation).
 *
 * If this test fails:
 *   1. Identify which config block in eslint.config.js shadows the
 *      missing selector / path.
 *   2. Either narrow that block's `files`/`ignores` so it stops
 *      matching the asserted file, OR migrate it to use
 *      `defineScopedDoctrine()` / `defineScopedImportDoctrine()`.
 *   3. NEVER add a `// eslint-disable` to silence this test — the
 *      whole point is that flat-config replacement is invisible
 *      without an explicit assertion.
 */

interface RestrictedSyntaxOption {
  selector?: string;
  message?: string;
}

interface RestrictedImportPath {
  name?: string;
  message?: string;
}

const eslint = new ESLint({
  cwd: path.resolve(__dirname, '../..'),
  overrideConfigFile: path.resolve(__dirname, '../..', 'eslint.config.js'),
  ignore: false,
});

async function getRestrictedSyntaxSelectors(filePath: string): Promise<string[]> {
  const config = (await eslint.calculateConfigForFile(filePath)) as {
    rules?: Record<string, unknown>;
  };
  const rule = config.rules?.['no-restricted-syntax'];
  if (!Array.isArray(rule)) return [];
  return rule
    .slice(1)
    .filter((opt): opt is RestrictedSyntaxOption => typeof opt === 'object' && opt !== null)
    .map((opt) => opt.selector ?? '')
    .filter(Boolean);
}

async function getRestrictedImportPaths(filePath: string): Promise<string[]> {
  const config = (await eslint.calculateConfigForFile(filePath)) as {
    rules?: Record<string, unknown>;
  };
  const rule = config.rules?.['no-restricted-imports'];
  if (!Array.isArray(rule)) return [];
  // Shape: ["error", { paths: [{name, message}, ...], patterns: [...] }]
  const opts = rule[1] as { paths?: RestrictedImportPath[] } | undefined;
  return (opts?.paths ?? [])
    .map((p) => p.name ?? '')
    .filter(Boolean);
}

// `labelFor` lives in src/test/lintLabel.ts so a dedicated unit test
// (src/test/lintLabel.test.ts) can assert label-quality guarantees
// against every entry in CONSOLIDATED_RESTRICTED_SYNTAX and
// PLATFORM_PRIMITIVE_PATHS — catches regressions where a future
// doctrine message produces an unreadable test name.
import { labelFor } from './lintLabel';

describe('eslint.config.js: flat-config resolution meta-test', () => {
  // ────────────────────────────────────────────────────────────────────
  // CONSOLIDATED_RESTRICTED_SYNTAX — assertions generated from the array
  // so adding a new selector to eslint.config.js automatically extends
  // coverage. No second-place-to-edit hazard.
  // ────────────────────────────────────────────────────────────────────
  describe('CONSOLIDATED_RESTRICTED_SYNTAX selectors survive on representative files', () => {
    // Representative files that should resolve every consolidated selector.
    // - src/App.tsx: matched by the global block only.
    // - src/components/home/HeroSection.tsx: also matched by the hero
    //   `defineScopedDoctrine` block (which appends — the meta-test asserts
    //   the helper concatenated correctly).
    // - src/components/platform/ui/PlatformButton.tsx: also matched by the
    //   platform import-doctrine block (verifies the import block does NOT
    //   shadow `no-restricted-syntax`, since they're separate rules).
    const REPRESENTATIVE_FILES = [
      'src/App.tsx',
      'src/components/home/HeroSection.tsx',
    ];

    for (const filePath of REPRESENTATIVE_FILES) {
      describe(`file: ${filePath}`, () => {
        for (const opt of CONSOLIDATED_RESTRICTED_SYNTAX) {
          const label = labelFor(opt);
          it(`keeps doctrine: ${label}`, async () => {
            const selectors = await getRestrictedSyntaxSelectors(filePath);
            expect(
              selectors.includes(opt.selector ?? ''),
              `Doctrine selector missing from resolved config for ${filePath}.\nExpected selector:\n  ${opt.selector}\nResolved selectors:\n${selectors.map((s) => `  - ${s}`).join('\n')}`,
            ).toBe(true);
          });
        }
      });
    }
  });

  // ────────────────────────────────────────────────────────────────────
  // PLATFORM_PRIMITIVE_PATHS — assertions generated from the array.
  // Asserts every banned import path survives on a representative
  // platform-layer file (matched by `defineScopedImportDoctrine`).
  // ────────────────────────────────────────────────────────────────────
  describe('PLATFORM_PRIMITIVE_PATHS bans survive on a platform-layer file', () => {
    const PLATFORM_FILE = 'src/components/platform/ui/PlatformButton.tsx';

    for (const opt of PLATFORM_PRIMITIVE_PATHS) {
      const label = labelFor({ message: opt.message, selector: opt.name });
      it(`keeps banned import: ${label}`, async () => {
        const paths = await getRestrictedImportPaths(PLATFORM_FILE);
        expect(
          paths.includes(opt.name ?? ''),
          `Platform-primitive import ban missing from resolved config for ${PLATFORM_FILE}.\nExpected: ${opt.name}\nResolved paths:\n${paths.map((p) => `  - ${p}`).join('\n')}`,
        ).toBe(true);
      });
    }
  });

  // ────────────────────────────────────────────────────────────────────
  // Targeted edge cases — these are NOT auto-generated because they
  // assert behavior on specific files that the array iteration above
  // doesn't cover (suppression semantics, fixture coverage, etc.).
  // ────────────────────────────────────────────────────────────────────
  it('keeps the Site Settings Event Ownership selector on the banned fixture', async () => {
    // The fixture is the file the smoke test lints; if the doctrine
    // selector is missing here, the smoke test will silently report
    // 0 violations and the canon is unenforced.
    const selectors = await getRestrictedSyntaxSelectors(
      'src/test/lint-fixtures/site-settings-event-banned.tsx',
    );
    expect(
      selectors.some((s) => s.includes('site-settings-draft-write')),
      `Site Settings Event Ownership selector missing from resolved config for the banned fixture. This usually means the rule's own \`ignores\` block excluded the fixture path.\nResolved selectors:\n${selectors.join('\n')}`,
    ).toBe(true);
  });

  it('applies the Site Settings rule to the owning module (suppression is per-line)', async () => {
    // The owning module is no longer excluded via `ignores`; instead each
    // dispatch site uses `// eslint-disable-next-line no-restricted-syntax`.
    const selectors = await getRestrictedSyntaxSelectors('src/lib/siteSettingsDraft.ts');
    expect(
      selectors.some((s) => s.includes('site-settings-draft-write')),
      'Site Settings rule should be active on src/lib/siteSettingsDraft.ts; the dispatch sites suppress it with inline eslint-disable comments.',
    ).toBe(true);
  });

  it('keeps the Promo Popup preview event selectors on the banned fixture', async () => {
    const selectors = await getRestrictedSyntaxSelectors(
      'src/test/lint-fixtures/promo-popup-events-banned.tsx',
    );
    expect(
      selectors.some((s) => s.includes('promo-popup-preview-reset')),
      `promo-popup-preview-reset selector missing from resolved config for the banned fixture.\nResolved selectors:\n${selectors.join('\n')}`,
    ).toBe(true);
    expect(
      selectors.some((s) => s.includes('promo-popup-preview-state')),
      `promo-popup-preview-state selector missing from resolved config for the banned fixture.\nResolved selectors:\n${selectors.join('\n')}`,
    ).toBe(true);
  });

  it('applies the Promo Popup preview event rules to the owning module (suppression is per-line)', async () => {
    const selectors = await getRestrictedSyntaxSelectors(
      'src/lib/promoPopupPreviewReset.ts',
    );
    expect(
      selectors.some((s) => s.includes('promo-popup-preview-reset')),
      'promo-popup-preview-reset rule should be active on the owning module; dispatch sites use inline eslint-disable comments.',
    ).toBe(true);
    expect(
      selectors.some((s) => s.includes('promo-popup-preview-state')),
      'promo-popup-preview-state rule should be active on the owning module; dispatch sites use inline eslint-disable comments.',
    ).toBe(true);
  });

  it('keeps the editor-section-hover selector on the banned fixture', async () => {
    const selectors = await getRestrictedSyntaxSelectors(
      'src/test/lint-fixtures/editor-section-hover-banned.tsx',
    );
    expect(
      selectors.some((s) => s.includes('editor-section-hover')),
      `editor-section-hover selector missing from resolved config for the banned fixture.\nResolved selectors:\n${selectors.join('\n')}`,
    ).toBe(true);
  });

  it('applies the editor-section-hover rule to the owning module (suppression is per-line)', async () => {
    const selectors = await getRestrictedSyntaxSelectors('src/lib/editorSectionHover.ts');
    expect(
      selectors.some((s) => s.includes('editor-section-hover')),
      'editor-section-hover rule should be active on src/lib/editorSectionHover.ts; the dispatch goes through dispatchOwnedEvent which carries an inline eslint-disable.',
    ).toBe(true);
  });

  it('keeps the hero-specific selector (alignment + shared component) on hero files', async () => {
    // The hero block appends two extraSelectors via defineScopedDoctrine.
    // Auto-iteration above covers the consolidated 5; this one asserts
    // the helper's concatenation actually appended the hero-specific 6th
    // and 7th. Anchored on a member-access fragment unique to each.
    const selectors = await getRestrictedSyntaxSelectors(
      'src/components/home/HeroSection.tsx',
    );
    expect(
      selectors.some((s) => s.includes("object.name='alignment'")),
      `Hero Alignment Canon selector missing from resolved config (defineScopedDoctrine extraSelectors did not append).\nResolved selectors:\n${selectors.join('\n')}`,
    ).toBe(true);
    expect(
      selectors.some((s) => s.includes('consultation_note_line')),
      `Hero shared-component selector missing from resolved config.\nResolved selectors:\n${selectors.join('\n')}`,
    ).toBe(true);
  });

  it('keeps the FocalPointPicker Isolation selectors on the banned fixture', async () => {
    // The fixture lives outside the canonical owner / consumer paths and
    // is the file the doctrine's smoke surface lints. If either selector
    // is missing here, a future PR reintroducing <FocalPointPicker>
    // outside MediaUploadInput will pass lint silently — the exact
    // regression the November 2026 hero consolidation closed.
    const selectors = await getRestrictedSyntaxSelectors(
      'src/test/lint-fixtures/focal-point-picker-banned.tsx',
    );
    expect(
      selectors.some((s) => s.includes("name.name='FocalPointPicker'")),
      `FocalPointPicker JSX-usage selector missing from resolved config for the banned fixture.\nResolved selectors:\n${selectors.join('\n')}`,
    ).toBe(true);
    expect(
      selectors.some((s) => s.includes("imported.name='FocalPointPicker'")),
      `FocalPointPicker import-specifier selector missing from resolved config for the banned fixture.\nResolved selectors:\n${selectors.join('\n')}`,
    ).toBe(true);
  });

  it('does NOT apply the FocalPointPicker ban to the canonical owner or consumer', async () => {
    // The owner (FocalPointPicker.tsx) defines the component and the
    // consumer (MediaUploadInput.tsx) renders it as an overlay. Both are
    // ignored by the doctrine block; this assertion guards against a
    // future maintainer dropping the `ignores` entries and breaking the
    // owner module's own self-reference.
    for (const ownerPath of [
      'src/components/dashboard/website-editor/inputs/FocalPointPicker.tsx',
      'src/components/dashboard/website-editor/inputs/MediaUploadInput.tsx',
    ]) {
      const selectors = await getRestrictedSyntaxSelectors(ownerPath);
      expect(
        selectors.every((s) => !s.includes("imported.name='FocalPointPicker'")),
        `FocalPointPicker import ban should NOT apply to ${ownerPath} — that file is the canonical owner / consumer. The doctrine's \`ignores\` block must list it.`,
      ).toBe(true);
    }
  });

  it('keeps the Global Overlay Stability import ban on the banned fixture', async () => {
    // The fixture lives outside src/components/** and is the file the
    // smoke surface lints. If this assertion fails, a future PR adding
    // `subscribeHeroAlignment` to a global FAB / Popup / Overlay /
    // Widget will pass lint silently — the exact regression the
    // PromotionalPopup canon (Nov 2026) closed.
    const paths = await getRestrictedImportPaths(
      'src/test/lint-fixtures/hero-alignment-signal-overlay-banned.tsx',
    );
    expect(
      paths.includes('@/lib/heroAlignmentSignal'),
      `Global Overlay Stability import ban missing from resolved config for the banned fixture.\nExpected: @/lib/heroAlignmentSignal\nResolved paths:\n${paths.map((p) => `  - ${p}`).join('\n')}`,
    ).toBe(true);
  });

  it('does NOT apply the Global Overlay Stability ban to non-overlay hero files', async () => {
    // The hero subtree may legitimately consume the alignment signal in
    // the future (e.g. a hero-internal reading-progress bar). The scope
    // intentionally targets *Fab* / *Popup* / *Overlay* / *Widget*
    // filenames, not the lib itself. Guard against a future maintainer
    // broadening the scope and breaking the hero subtree.
    const paths = await getRestrictedImportPaths(
      'src/components/home/HeroSlideRotator.tsx',
    );
    expect(
      paths.every((p) => p !== '@/lib/heroAlignmentSignal'),
      `Global Overlay Stability ban should NOT apply to non-overlay hero files. The doctrine is scoped to filename patterns, not the lib path. Resolved paths:\n${paths.map((p) => `  - ${p}`).join('\n')}`,
    ).toBe(true);
  });
});
